### ISSUE TITLE
Question of translating UI

### ISSUE THREAD

**Issue by sgqy** [Rare25/DereEditor#3]
I'd like to translate the UI into Chinese.
But the strings are hard-coded. It seems the only way to translate is making a fork version.
Is there a plan to get the strings into resource file for multi-language use?

Everyone can reply in Japanese or English.
Best Wishes. :)

**Comment by grainrigi** [comment]
I've made a pull request which implement multilingual handling.
https://github.com/Rare25/DereEditor/pull/4

**Comment by sgqy** [comment]
Oh, it is a big change!

I complished the translation and put it here: [zh-cn.zip](https://github.com/Rare25/DereEditor/files/1312974/zh-cn.zip)

Anyway, thanks for your new platform!

But... there's some problem about font...
Some characters seems not exist in 'mplus' font.
![image of font problem](https://user-images.githubusercontent.com/4893302/30574732-9890da74-9d2e-11e7-9696-65e6341cd99d.PNG)

**Comment by Rare25** [comment]
Thanks for your translation!
I would like to solve the font problem in some way.
May I add your name and TwitterID in readme?

**Comment by sgqy** [comment]
Yeah, it's my honor 😆 .

**Comment by Rare25** [comment]
I solved that problem.
Support a font change with the new release.
https://github.com/Rare25/DereEditor/releases/tag/0.11.1

**Comment by sgqy** [comment]
Then the readme.txt can add more information.
en:
```
■Change UI font
If you changed language of UI, it is better to change font together.
(Though most fonts include English characters xD.)
Fill in 'fontname=' under '[Locale]' in 'config.ini' would do that work.
(The font name can include spaces without quotes.)

■Config example
When selecting English, you can config the program like below, change it to fit your own machine.
[SimulatorPath]
deleste=..\__deleste\DelesteSimulator.exe
[Locale]
localefile=locale\en.dat
fontname=Segoe UI
```
zh-CN:
```
■修改界面字体
为了配合您选择的界面语言，界面字体同样需要修改。
在 config.ini 中 [Locale] 项下的 fontname= 后面填写字体名称即可（可包含空格而无需引号）。

■配置文件示例
选择中文配置时可以如下设置，请将相关信息修改为符合您机器的样子。
[SimulatorPath]
deleste=..\__deleste\DelesteSimulator.exe
[Locale]
localefile=locale\zh_cn.dat
fontname=Microsoft YaHei UI
```

ja:
```
（config.ini に何も書かないのはデフォルトの設定みたいです。
でも一応 [SimulatorPath] の deleste は設定すべきでしょう。）
```

**Comment by sgqy** [comment]
Another advice.
For example, 222.22 bpm, 04:30 length (you-know-what:laughing:). The count of bar exceeds 200. Maybe better to set it bigger (e.g. 300+)?
![image](https://user-images.githubusercontent.com/4893302/34353687-9cd6e65e-ea64-11e7-96e2-13e82c873994.png)

**Comment by Rare25** [comment]
Thanks for the advice.
